// Copyright (c) 2012-2016 Saarland University
// All rights reserved.
//
// Author: Konrad Jamrozik, jamrozik@st.cs.uni-saarland.de
//
// This file is part of the "DroidMate" project.
//
// www.droidmate.org

package org.droidmate.plugin_hook;

import android.content.Context;

// !!!!! =================================================================
// !!!!! DO NOT EDIT THIS FILE !!!
// !!!!! =================================================================
// !!!!! Instead, run full gradle rebuild (see README.md) or do:
// !!!!! 
// !!!!!   cd repo/droidmate/dev/droidmate 
// !!!!!   ./gradlew :projects:plugin-api-hook:compileJava 
// !!!!! 
// !!!!! This will generate HookPlugin.java in the same directory as this class. Edit that file instead.

/**
 * Please see {@link HookPluginExample} for an example implementation.
 */
// These warnings are suppressed because this class is only a stub of an actual implementation.
@SuppressWarnings({"unused", "Duplicates", "FieldCanBeLocal", "WeakerAccess"})
public class HookPluginTemplate implements IHookPlugin
{

  public void init(Context context) 
  {
  }

  public void hookBeforeApiCall(String apiLogcatMessagePayload)
  {
  }

  public Object hookAfterApiCall(String apiLogcatMessagePayload, Object returnValue)
  {
    return returnValue;
  }

  public void finalizeHookPlugin()
  {
  }
}

