// Copyright (c) 2012-2016 Saarland University
// All rights reserved.
//
// Author: Konrad Jamrozik, jamrozik@st.cs.uni-saarland.de
//
// This file is part of the "DroidMate" project.
//
// www.droidmate.org

package org.droidmate.plugin_hook;

import org.jetbrains.annotations.NotNull;

// !!!!! !!!!! !!!!!
// !!!!! !!!!! !!!!! DO NOT EDIT THIS FILE. 
// !!!!! !!!!! !!!!! Instead, edit HookPlugin class. Run 'gradlew :projects:plugin-api-hook:assemble' to generate it.
// !!!!! !!!!! !!!!! DO NOT EDIT THIS FILE.
// !!!!! !!!!! !!!!!
public class HookPluginTemplate implements IHookPlugin
{
  public void before(@NotNull String objectClass)
  {
    // !!!!! !!!!! !!!!!
    // !!!!! !!!!! !!!!! DO NOT EDIT THIS FILE. 
    // !!!!! !!!!! !!!!!
    System.out.println("objectClass from hook: "+ objectClass);
  }
}
